name: Build Windows Executable

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: windows-latest # Use a Windows runner

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Specify Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build executable with PyInstaller
      run: |
        pyinstaller --onefile --windowed --name FormulaireQuiz app.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: FormulaireQuiz-Windows-Executable
        path: dist/FormulaireQuiz.exe # Path to the generated .exe file 